### ISSUE TITLE
Insufficient number of iterations

### ISSUE THREAD

**Issue by tahmetcetin** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Drone-Control#4]
When training a example model with Yolo, the training graph looks constant for 2000 iterations, it seems like it needs more iterations to start learning, can you increase the number of iterations? @yagmurera

**Comment by yagmurera** [comment]
According to the recommended value, generally up to 3 classes, the number of 6000 iterations was sufficient.  When I tried it with the recommended 6000 iterations, the model training was successful.

**Comment by yagmurera** [comment]
According to the recommended value, generally up to 3 classes, the number of 6000 iterations was sufficient. When I tried it with the recommended 6000 iterations, the model training was successful.

**Comment by yagmurera** [comment]
According to the recommended value, generally up to 3 classes, the number of 6000 iterations was sufficient. When I tried it with the recommended 6000 iterations, the model training was successful.
