### ISSUE TITLE
Image Labelling

### ISSUE THREAD

**Issue by tahmetcetin** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Drone-Control#5]
While preparing the pictures necessary for our model to learn, a large number of different pictures of specific objects are required, about 1000 pictures will need to be labeled, let's divide 334 333 333 as the number of pictures. @yagmurera , @smerii

**Comment by yagmurera** [comment]
We divided it between us because there were too many pictures to be labeled.
